WebApplication/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Folio.Web.Controllers
{
    [RoutePrefix("cal")]
    public class CalendarController : Controller
    {
        private readonly IResourceRepository repository;

        public CalendarController(IResourceRepository repository)
        {
            this.repository = repository;
        }

        [Route()]
        public ActionResult Years()
        {
            var items =
                from year in Enumerable.Range(1980, 2010 - 1980 + 1)
                select new CalendarItem
                {
                    Url = Url.Action("Months", new { Year = year }),
                    Label = year.ToString(),
                    RecordCount = repository.ByDateTag(DateTag.FromYear(year), DateTag.Matching.Inclusive).Count(),
                };
            ViewBag.Title = Resources.CalendarTitle;
            return View("List", items);
        }

        [Route("{year:int}")]
        public ViewResult Months(int year)
        {
            var items =
                from month in Enumerable.Range(1, 12)
                select new CalendarItem
                {
                    Url = Url.Action("Days", new { Year = year, Month = month }),
                    Label = CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(month),
                    RecordCount = repository.ByDateTag(DateTag.FromYearAndMonth(year, month), DateTag.Matching.Inclusive).Count(),
                };
            ViewBag.Title = year.ToString();
            ViewBag.Breadcrumbs = new MenuItem[]
            {
                new MenuItem { Url = Url.Action("Years"), Label = Resources.CalendarTitle },
            };
            return View("List", items);
        }

        [Route("{year:int}-{month:int}")]
        public ViewResult Days(int year, int month)
        {
            var items =
                from day in Enumerable.Range(1, DateTime.DaysInMonth(year, month))
                select new CalendarItem
                {
                    Url = Url.Action("Index", "Record", new { Year = year, Month = month, Day = day }),
                    Label = day.ToString(),
                    RecordCount = repository.ByDateTag(DateTag.FromDate(year, month, day), DateTag.Matching.Inclusive).Count(),
                };
            ViewBag.Title = string.Format("{0}, {1}", year, CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(month));
            ViewBag.Breadcrumbs = new MenuItem[]
            {
                new MenuItem { Url = Url.Action("Years"), Label = Resources.CalendarTitle },
                new MenuItem { Url = Url.Action("Months", new { Year = year }), Label = year.ToString() },
            };
            return View("List", items);
        }
    }
}

WebApplication/Views/Shared/RecordList.cshtml
@model IEnumerable<Folio.Resource>

<div class="list-group">
    @foreach (var item in Model)
    {
        Html.RenderPartial("RecordListItem", item);
    }
</div>

WebApplication/Views/Shared/RecordListItem.cshtml
@model Folio.Resource

<a href="@Model.Url.AbsoluteUri" target="_blank" class="list-group-item">

    <div class="data f16">
        <h4><span class="fa fa-@Html.RecordTypeIcon(Model.Type)" aria-hidden="true"></span>&nbsp;@Model.Title</h4>
        <p>@Model.Description</p>

        <p><small>@Model.Url.ToString() <i class="fa fa-external-link"></i></small></p>

        @foreach (var tag in Model.DateTags)
        {
            <span class="label label-default"><i class="fa fa-calendar"></i>&nbsp;@tag.ToString()</span>
        }

    </div>
</a>

WebApplication/Views/Shared/_Layout.cshtml
@{
    ViewBag.PageTitle = ViewBag.Title;
    if (!String.IsNullOrWhiteSpace(ViewBag.Title))
    {
        ViewBag.PageTitle += " — ";
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.PageTitle@Resources.ProjectTitle</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(Resources.ProjectTitle, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Resources.CalendarTitle, "Years", "Calendar")</li>
                    <li>@Html.ActionLink(Resources.AboutTitle, "About", "Home")</li>
                    <li>@Html.ActionLink(Resources.ContactTitle, "Contact", "Home")</li>
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="input-group" style="width: 200px;">
                        <input type="text" class="form-control" placeholder="@Resources.SearchPlaceholder" id="query">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit" aria-label="@Resources.SearchButton"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                        </span>
                    </div>
                </form>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @if (ViewBag.Breadcrumbs is IEnumerable<MenuItem>)
        {
            <ol class="breadcrumb">
                @foreach (var item in (IEnumerable<MenuItem>)ViewBag.Breadcrumbs)
                {
                    <li><a href="@item.Url">@item.Label</a></li>
                }
                <li class="active">@ViewBag.Title</li>
            </ol>
        }
        @if (!String.IsNullOrWhiteSpace(ViewBag.Title))
        {
            <div class="page-header">
                <h1>@ViewBag.Title</h1>
            </div>
        }
        @RenderBody()
        <hr />
        <footer></footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>